/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grpc.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import grpc.example.client.GrpcClient;

import java.io.IOException;

@RunWith(JUnit4.class)
public class AppTest {
    private final int PORT = 8900;
    @Test
    public void testGrpcServer() throws IOException, InterruptedException {

        App classUnderTest = new App(PORT);
        classUnderTest.start();

        class MyThread extends Thread {

            @Override
            public void run() {

                System.out.println("Thread Running");
                try {
                    classUnderTest.start();
                } catch (IOException e) {
                    fail("IOException Caught " + e);
                }
            }

            public void stopServer() throws InterruptedException {

                classUnderTest.stop();

            }

        }
        MyThread thread = new MyThread();
        GrpcClient client = new GrpcClient("localhost", PORT);
        thread.start();
        String response = client.searchRequest("test", "email_id", 10, 1);
        assertEquals(response, "SearchResponseemail_id");
        thread.stopServer();

    }
}
