/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grpc.example;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import java.io.IOException;

import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

import grpc.example.server.GrpcServer;

public class App {
    private static final Logger logger = Logger.getLogger(App.class.getName());

    private final int port;
    private final Server server;

    /**
     * Create a RouteGuide server listening on {@code port} using
     * {@code featureFile} database.
     */
    public App(int port) throws IOException {
        this(ServerBuilder.forPort(port), port);
    }

    public App(ServerBuilder<?> serverBuilder, int port) {
        this.port = port;
        server = serverBuilder.addService(new GrpcServer()).build();
    }

    /** Start serving requests. */
    public void start() throws IOException {
        server.start();
        logger.info("Server started, listening on " + port);
        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                // Use stderr here since the logger may have been reset by its JVM shutdown
                // hook.
                System.err.println("*** shutting down gRPC server since JVM is shutting down");
                try {
                    App.this.stop();
                } catch (InterruptedException e) {
                    e.printStackTrace(System.err);
                }
                System.err.println("*** server shut down");
            }
        });
    }

    /** Stop serving requests and shutdown resources. */
    public void stop() throws InterruptedException {
        if (server != null) {
            server.shutdown().awaitTermination(30, TimeUnit.SECONDS);
        }
    }

    /**
     * Await termination on the main thread since the grpc library uses daemon
     * threads.
     */
    private void blockUntilShutdown() throws InterruptedException {
        if (server != null) {
            server.awaitTermination();
        }
    }

    public static void main(String[] args) throws Exception {
        App server = new App(8980);
        server.start();
        server.blockUntilShutdown();
    }
}
